config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  resources :admins do
    resources :courses
    resources :instructors
    resources :students
    resources :cohorts
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  get 'admins', to: 'pages#home'


end

app/views/admins/edit.html.erb
<div class="forms">
  <div class="forms-grid">
    <div>
      <h2 class="center">Edit Profile</h2>

      <% if @admin.errors.any? %>
      <% @admin.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      <% end %>

      <%=form_for(@admin) do |f|%>
      <p><%= f.text_field :first_name, placeholder: "First name" %></p>

      <p><%= f.text_field :last_name, placeholder: "Last name" %></p>

      <p><%= f.email_field :email, placeholder: "Email address" %></p>

      <p><%= f.password_field :password, placeholder: "Password" %> <br>
        <%= f.password_field :password, placeholder: "Confirm password" %></p>

        <p><%= f.label :avatar%> <br>
          <%= f.file_field :avatar, direct_upload: true %>
        </p>

        <p>
          <%= f.submit "Update Information", class: "btn btn-account" %>
        </p>

        <%end%>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<p>Find me in app/views/admins/index.html.erb</p>

app/views/admins/new.html.erb
<body id="account-bg">

<style media="screen">
input[type=text], input[type=email], input[type=password]{
  width: 75%;
  background-color: #e3e3e3;
  font-size: .87em;
  padding: 10px 15px;
  margin: 8px 0;
  box-sizing: border-box;
}

input[type=text]{
  background-image: url("https://cdn3.iconfinder.com/data/icons/seo-marketing-19/32/SEO-10-512.png");
  background-size: 12%;
  background-position: 5%;
  background-repeat: no-repeat;
  padding-left: 14%;
}

input[type=email]{
  background-image: url("https://cdn3.iconfinder.com/data/icons/linecons-free-vector-icons-pack/32/mail-512.png");
  background-size: 12%;
  background-position: 5%;
  background-repeat: no-repeat;
  padding-left: 14%;
}

input[type=password]{
  background-image: url("https://cdn3.iconfinder.com/data/icons/linecons-free-vector-icons-pack/32/lock-512.png");
  background-size: 11%;
  background-position: 5%;
  background-repeat: no-repeat;
  padding-left: 14%;
}
input[type=submit] {
  width: 75%;
  display:inline-block;
  position:relative;
  padding:10px 25px;
  border:2px solid #ffecf6;
  color:#ffecf6;
  background-color: #f16f9d;
  font-size:1.1em;
  text-decoration:none;
  transition: color 0.4s
}

input[type=submit]:hover {
  color:#f16f9d;
  background-color: #ffecf6;
}
</style>

  <div class="container">
    <div class="sub-container">
      <div class="account-grid center">
        <div class="animate-down">
          <h1>Sign Up</h1>

          <%= form_for(@admin) do |f|%>
            <%= f.text_field :first_name, placeholder: "First Name" %>

            <%= f.text_field :last_name, placeholder: "Last Name" %>

              <%= f.email_field :email, placeholder: "Email Address" %>

              <%= f.password_field :password, placeholder: "Password" %>
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %> <br>

              <%= f.submit "Create Account"%>

            <%end%>
          </div>

          <div class="animate-up">
            <h1>Luna's School</h1>
            <!-- <img src="/assets/logo.png"> -->
            <h2>Create An Account</h2>
            <h4>Already Have An Account?</h4>
            <h4><%= link_to 'Sign In', login_path, class: 'btn-account'%></h4>

            <% if @admin.errors.any? %>
            <% @admin.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>

app/views/admins/show.html.erb
<% if !logged_in?%>
<div class="container">
  <div class="sub-container center">
    <div class="animate-down">
      <h1>You have no access to this site!!</h1>
      <%= link_to 'Sign Up', new_admin_path, class: "btn btn-primary"%>
      <%= link_to 'Log In', login_path, class: "btn btn-primary"%>
    </div>
  </div>
</div>
<% else  %>

<div class="profile center">
  <div class="profile-card center">
    <div>
      <%= @admin.avatar.attachment.nil? ? content_tag(:div, "#{@admin.initials}", class: "default"): image_tag(@admin.avatar, class: "profile-img") if session[:user_id] %>
    </div>

    <div>
      <h1><%=@admin.first_name.capitalize%></h1>

      <h4>Full Name: &nbsp <%=@admin.full_name%></h4>
      <h4>Email: &nbsp <%=@admin.email%></h4>
      <br> <hr>
      <a class="icons" href="<%= edit_admin_path %>">
        <img src="https://img.icons8.com/bubbles/500/000000/edit.png">
      </a> &nbsp &nbsp &nbsp
      <a class="icons" href="<%= logout_path %>">
        <img src="https://img.icons8.com/bubbles/500/000000/shutdown.png">
      </a>
    </div>
  </div>
</div>
<% end %>