config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  resources :admins do
    resources :courses
    resources :instructors
    resources :students
    resources :cohorts
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  get 'admins', to: 'pages#home'


end

app/models/instructor.rb
class Instructor < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :education, presence: true
  # validates_uniqueness_of :email, presence: true
  validates :age, inclusion: {in: 1..150, :message => "needs to be greater than 1 and less than 150"}
  validates :salary, numericality: {greater_than: 0, :message => "can't be less than 0"}
  has_many :cohorts
  has_one_attached :avatar

  def full_name
    full_name = self.first_name.capitalize + " " + self.last_name.capitalize
    return full_name
  end

  def initials
    initials = self.first_name.chars.first.upcase + self.last_name.chars.first.upcase
  end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def new
    @admin = Admin.find(params[:admin_id])
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(inst_params)

    if @instructor.valid?
      @instructor.save
      flash[:success] = "Instructor Added!"
      redirect_to admin_instructors_path
    else
      puts @instructor.errors.messages
      flash[:error] = "#{@instructor.errors.full_messages}"
      redirect_to new_admin_instructor_path
    end
  end

  def index
    @instructor = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def edit
    @admin = Admin.find(params[:admin_id])
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])

    if @instructor.update_attributes(inst_params)
      flash[:success] = "Instructor Information Updated!"
      redirect_to admin_instructors_path
    else
      puts @instructor.errors
      flash[:error] = "#{@instructor.errors.full_messages}"
      redirect_to edit_admin_instructor_path
    end
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy

    respond_to do |format|
      format.html
      format.js
    end

    redirect_to admin_instructors_path

  end

  private

  def inst_params
    params.require(:instructor).permit(:first_name, :last_name,
                                    :age, :salary,
                                    :education,
                                    :email, :password,
                                    :avatar, :cohort_id)
  end

end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/destroy.js.erb
var deleteitem = document.getElementById('instructor-<%=@instructor.id%>');
deleteitem.remove()

app/views/instructors/edit.html.erb
<div class="forms">
  <div class="forms-grid">
    <div>
      <h1 class="center"><%=@instructor.first_name%> <%=@instructor.last_name%></h1>
      <h2>Edit Information</h2>


      <%=form_for([@admin, @instructor]) do |f|%>
      <p><%= f.label :first_name, "First Name"%> <br>
        <%= f.text_field :first_name%></p>

        <p><%= f.label :last_name, "Last Name"%> <br>
          <%= f.text_field :last_name%></p>

          <p><%= f.label :age%> <br>
            <%= f.number_field :age%></p>

            <p><%= f.label :salary%> <br>
              <%= f.number_field :salary%></p>

              <p><%= f.label :education%> <br>
                <%= f.select :education, ["Highschool Diploma", "Bachelor's Degree", "Master's Degree", "Ph.D"], :include_blank => true %>
              </p>

              <p><%= f.label :avatar%> <br>
                <%= f.file_field :avatar, direct_upload: true %>
              </p>

                <p class="center">
                  <%= f.submit "Update Information", class: "btn btn-account" %>
                </p>

                <%end%>
                <div class="center">
                  <a class="icons" href="<%= admin_instructors_path%>">
                    <img src="https://img.icons8.com/bubbles/500/000000/restart.png">
                  </a>

                  <a class="icons" href="<%= root_path%>">
                    <img src="https://img.icons8.com/bubbles/500/000000/home.png">
                  </a>
                </div>
    </div>
  </div>
</div>

app/views/instructors/index.html.erb
<div class="container">
  <div class="inst-page-title center">
    <h1>Instructors</h1>
    <a class="btn btn-secondary" href="<%= new_admin_instructor_path %>">Add New Instructor</a>
  </div> <br>

  <div class="inst-table">
    <div class="inst-table-header">
      <div></div>
      <div>Full Name</div>
      <div>Age</div>
      <div>Education</div>
      <div class="center">Salary</div>
      <div></div>
      <div></div>
      <div></div>
    </div>

    <div class="inst-body">
      <%@instructor.reverse.each do |inst|%>
      <div class="inst-row" id="instructor-<%=inst.id%>">
        <%= inst.avatar.attachment.nil? ? content_tag(:div, "#{inst.initials}", class: "inst-table-img"): image_tag(inst.avatar, class: "table-img") if session[:user_id] %>
        <div><%=inst.full_name%></div>
        <div><%=inst.age%></div>
        <div><%=inst.education%></div>
        <div class="center">$<%=inst.salary%></div>
        <div class="center">
          <a class="inst-table-icon" href="<%= admin_instructor_path(session[:user_id], inst) %>">
            <img src="https://img.icons8.com/bubbles/500/000000/contact-card.png">
          </a>
        </div>
        <div class="center">
          <a class="inst-table-icon" href="<%= edit_admin_instructor_path(session[:user_id], inst) %>">
            <img src="https://img.icons8.com/bubbles/500/000000/edit.png">
          </a>
        </div>

        <div class="center">
          <%= link_to admin_instructor_path(session[:user_id], inst), remote: true, method: :delete, data: {confirm: 'Are you sure?'}, class: 'inst-table-icon' do %>
          <%= image_tag("https://img.icons8.com/bubbles/500/000000/minus.png",) %>
          <% end %>
        </div>
      </div>
      <%end%>
    </div>
  </div>

</div>

app/views/instructors/new.html.erb
<%if logged_in?%>
<div class="forms">
  <div class="forms-grid">
    <div>
      <h1>Create Instructor</h1>
      <%=form_for([@admin, @instructor]) do |f|%>
      <p><%= f.label :first_name, "First Name"%> <br>
        <%= f.text_field :first_name%></p>

        <p><%= f.label :last_name, "Last Name"%> <br>
          <%= f.text_field :last_name%></p>

          <p><%= f.label :age%> <br>
            <%= f.number_field :age%></p>

            <p><%= f.label :salary%> <br>
              <%= f.number_field :salary%></p>

              <p><%= f.label :education%> <br>
                <%= f.select :education, ["Highschool Diploma", "Bachelor's Degree", "Master's Degree", "Ph.D"], :include_blank => true %></p>

                <p class="center">
                  <%= f.submit "Create Instructor", class: "btn btn-account"%>
                </p>

                <%end%>
              <div class="center">
                  <a class="icons" href="<%= admin_instructors_path%>">
                    <img src="https://img.icons8.com/bubbles/500/000000/restart.png">
                  </a>

                  <a class="icons" href="<%= root_path%>">
                    <img src="https://img.icons8.com/bubbles/500/000000/home.png">
                  </a>
              </div>
        </div>
    </div>
</div>
<%end%>

app/views/instructors/show.html.erb
<div class="profile center">
  <div class="profile-card center">
    <div>
      <%= @instructor.avatar.attachment.nil? ? content_tag(:div, "#{@instructor.initials}", class: "default"): image_tag(@instructor.avatar, class: "profile-img") if session[:user_id] %>
    </div>

    <div>
      <h1><%=@instructor.first_name.capitalize%>'s Profile</h1>

      <h4>Full Name: &nbsp <%=@instructor.full_name%></h4>
      <h4>Age: &nbsp <%=@instructor.age%></h4>
      <h4>Education: &nbsp <%=@instructor.education%></h4>
      <hr>
      <a class="icons" href="<%= edit_admin_instructor_path %>">
        <img src="https://img.icons8.com/bubbles/500/000000/edit.png">
      </a> &nbsp &nbsp &nbsp
      <span class="icons">
        <%= link_to admin_instructor_path(@instructor), remote: true, method: :delete, data: {confirm: 'Are you sure?'} do %>
        <%= image_tag("https://img.icons8.com/bubbles/100/000000/delete.png") %>
        <% end %>
      </span>  &nbsp &nbsp &nbsp
      <a class="icons" href="<%= admin_instructors_path %>">
        <img src="https://img.icons8.com/bubbles/500/000000/transaction-list.png">
      </a>

    </div>
  </div>
</div>