config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  resources :admins do
    resources :courses
    resources :instructors
    resources :students
    resources :cohorts
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  get 'admins', to: 'pages#home'


end

app/views/pages/home.html.erb
<div class="container">

  <% if session[:user_id] != nil%>
  <h1 class="center">Dashboard</h1>
  <hr>
  <br> <br>

  <div class="dashboard">

    <div class="card">
      <div class="card-grid">
        <div class="card-top center">
          <a href="<%=admin_courses_path(session[:user_id])%>">
            <img src="https://areason2write.files.wordpress.com/2010/09/books-in-stack.png">
          </a>
          <h2 class="center">Courses</h2>
        </div>
        <div class="card-bottom center">
          <div>
            <p><%= link_to 'Create Course', new_admin_course_path(session[:user_id])%></p>
          </div>
          <div>
            <p><%= link_to 'View Courses', admin_courses_path(session[:user_id])%></p>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-grid">
        <div class="card-top center">
          <a href="<%=admin_students_path(session[:user_id])%>">
            <img src="https://openclipart.org/download/284854/publicdomainq-0004934crltvo.svg">
          </a>
          <h2 class="center">Students</h2>
        </div>
        <div class="card-bottom center">
          <div>
            <p><%= link_to 'Add Student', new_admin_student_path(session[:user_id])%></p>
          </div>
          <div>
            <p><%= link_to 'View Students', admin_students_path(session[:user_id])%></p>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-grid">
        <div class="card-top center">
          <a href="<%=admin_instructors_path(session[:user_id])%>">
            <img src="https://openclipart.org/image/2400px/svg_to_png/295930/publicdomainq-instruct.png">
          </a>
          <h2 class="center">Instructors</h2>
        </div>
        <div class="card-bottom center">
          <div>
            <p><%= link_to 'Add Instructor', new_admin_instructor_path(session[:user_id])%></p>
          </div>
          <div>
            <p><%= link_to 'View Instructors', admin_instructors_path(session[:user_id])%></p>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-grid">
        <div class="card-top center">
          <a href="<%=admin_cohorts_path(session[:user_id])%>">
            <img src="http://www.clker.com/cliparts/7/f/5/1/128165808084466705classroom.svg.hi.png">
          </a>
          <h2 class="center">Cohorts</h2>
        </div>
        <div class="card-bottom center">
          <div>
            <p><%= link_to 'Add Cohort', new_admin_cohort_path(session[:user_id])%></p>
          </div>
          <div>
            <p><%= link_to 'View Cohorts', admin_cohorts_path(session[:user_id])%></p>
          </div>
        </div>
      </div>
    </div>

  </div>

  <% end %>