config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  resources :admins do
    resources :courses
    resources :instructors
    resources :students
    resources :cohorts
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  get 'admins', to: 'pages#home'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdminPanel</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div id="alerts" class="center animate-up">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>

  <% if logged_in?%>
  <nav class="sidenav">
    <a href="/">
      <h3>Luna's School</h3>
      <!-- <img src="/assets/logo.png"> -->
    </a>
    <ul>
      <li><a href="<%=admin_path(session[:user_id])%>">My Profile</a></li>
      <li ><a href="<%=root_path(session[:user_id])%>">Dashboard</a></li>
      <li ><a href="<%=admin_courses_path(session[:user_id])%>">Courses</a></li>
      <li ><a href="<%=admin_students_path(session[:user_id])%>">Students</a></li>
      <li ><a href="<%=admin_instructors_path(session[:user_id])%>">Instructors</a></li>
      <li ><a href="<%=admin_cohorts_path(session[:user_id])%>">Cohorts</a></li>
      <li><a href="<%=logout_path%>">Log Out</a>
      </ul>
    </nav>
    <%end%>

    <div class="main">
      <%= yield %>
    </div>

    <script type="text/javascript">
      $('.chosen-select').chosen()
    </script>

  <script type="text/javascript">
    window.addEventListener('load', function(){
      console.log("works");
      setTimeout(function(){
        var alert = document.getElementById('alerts');
        alert.classList.add('hidden');
      },2000)
    });
  </script>

  </body>
  </html>